FROM apache/airflow:2.9.0

USER root
RUN apt-get update && apt-get install -y build-essential && apt-get clean

USER airflow

# This tells Docker to look at the ROOT of the project context for the file
COPY requirements.txt /opt/airflow/requirements.txt

RUN pip install --no-cache-dir -r /opt/airflow/requirements.txt

WORKDIR /opt/airflow